version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4141:4141"
    volumes:
      - .:/app
    environment:
      - ANTHROPIC_API_KEY=your_claude_api_key
      - OPENAI_API_KEY=your_openai_api_key
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    command: uvicorn main:app --host 0.0.0.0 --port 4141

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
